CREATE ROLE admin WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:tgTEv4ZnVTbb8nwJrRU6kA==$1OYfL7KMWXFlcDWTnGd1/SNjbb1y8g1znZlxVnSIzuI=:eRDhd+cgttC1Ys5IrvwO13rO0S6zHWVXQpo5Jfj/kRs=';

CREATE ROLE "Manager" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:sWpx25cuqy9CDlhEFCHqfg==$YBf97/UpQ9YZFrX7joM2Za6e3DpANfZFpgTGV3KBr9E=:z7Fv4jwckgIdMrFtV4iR6tPCFFVKpIrUo5GBhuTm6qc=';

CREATE ROLE "Client" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:Ykc7PhH0cYEzEuj9CP06tA==$2oVDqKrvqpQsCDcyyZu1xDc2wow3xvZQnWkpqQLB7SQ=:k8GDjrJFhSwxY/mRlRzXGeINN2i/9M8mFzcSL/hMkKE='