-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;
CREATE TABLE "ticket" (
  "ticket_id" integer PRIMARY KEY,
  "event" integer,
  "holl" integer,
  "zone" integer,
  "date_of_purchase" timestamp
);

CREATE TABLE "event" (
  "event_id" integer PRIMARY KEY,
  "event_date" timestamp,
  "group" integer,
  "place" integer
);

CREATE TABLE "group" (
  "group_id" integer PRIMARY KEY,
  "group_name" varchar,
  "music_style" varchar,
  "est" timestamp
);

CREATE TABLE "musician" (
  "musician_id" integer PRIMARY KEY,
  "group" integer,
  "executor_name" varchar,
  "tool_type" varchar,
  "BIO" varchar
);

CREATE TABLE "holl" (
  "holl_id" integer PRIMARY KEY,
  "holl_name" varchar
);

CREATE TABLE "zone" (
  "zone_id" integer PRIMARY KEY,
  "description" varchar
);

CREATE TABLE "place" (
  "place_id" integer PRIMARY KEY,
  "description" varchar
);

CREATE TABLE "users" (
  "id" integer PRIMARY KEY,
  "login" varchar,
  "password" varchar
);

CREATE TABLE "audit_log" (
  "id" integer PRIMARY KEY,
  "login" varchar,
  "event_type" varchar,
  "event_timestamp" timestamp
);

ALTER TABLE "ticket" ADD FOREIGN KEY ("event") REFERENCES "event" ("event_id");

ALTER TABLE "event" ADD FOREIGN KEY ("group") REFERENCES "group" ("group_id");

ALTER TABLE "event" ADD FOREIGN KEY ("place") REFERENCES "place" ("place_id");

ALTER TABLE "musician" ADD FOREIGN KEY ("group") REFERENCES "group" ("group_id");

ALTER TABLE "ticket" ADD FOREIGN KEY ("holl") REFERENCES "holl" ("holl_id");

ALTER TABLE "ticket" ADD FOREIGN KEY ("zone") REFERENCES "zone" ("zone_id");

END;